### ISSUE TITLE
Basic visual UI design for all screens 

### ISSUE THREAD

**Issue by deepaklodhadev** [next-demo/doctor-appointment-ui#3]
**-This is basic visual UI design and flow of project. 
-It's design in Microsoft Document
-Also Requirement of data(Mock) in MySQL table**
[Doc Appointment.docx](https://github.com/next-demo/doctor-appointment-ui/files/9225461/Doc.Appointment.docx)
.

**Comment by deepaklodhadev** [comment]
I have completed this task successfully #3

**Comment by murugan425** [comment]
Good Job @sdkosm  - converting the requirement to a design document with user flow., instead of word/ppt try the tools like drawio in future.

**Comment by deepaklodhadev** [comment]
Sure! @murugan425  For ER diagram, I used lucidchart.com

**Comment by deepaklodhadev** [comment]
**This is last and final UI Design after corrections.**

[Doc Appointment1.0.pdf](https://github.com/next-demo/doctor-appointment-ui/files/9300196/Doc.Appointment1.0.pdf)
